### ISSUE TITLE
Running the notebooks

### ISSUE THREAD

**Issue by RearrangedLetters** [kalmarek/2306.12358#3]
@kalmarek here are some things in noticed when running the notebooks.

- [ ] In Simply laced diagrams it says "A jupyter server may then be launched within the directory Chevalley_replication ...". The directory Chevalley_replication is presumably the old name of the project and no longer exists?
- [ ] In Simply laced diagrams in cell [24] and somewhere in the other notebooks: Under "Solving the problem numerically" I get "WARNING: could not import SCS_MKL_jll.MKL_jll into SCS" but the optimization still succeeds, so this probably doesn't mater.

Everything else worked as expected!

**Comment by kalmarek** [comment]
@RearrangedLetters thanks for running those;

the first issue is fixed by #4;
the second is upstream problem at the moment: https://github.com/jump-dev/SCS.jl/issues/278
